import type { StoreProductWithListing } from "@lib/data/products"

type MockListing = {
  title: string
  handle: string
  description: string
  category: string
  location: string
  quantity: string
  unit: string
  availability: string
  condition: string
  price: number
  thumbnail: string
}

const listings: MockListing[] = [
  {
    title: "Organic jasmine rice",
    handle: "mock-organic-jasmine-rice",
    description: "New season grain, cleaned and bagged for pickup.",
    category: "Produce",
    location: "Kampong Cham",
    quantity: "1,200",
    unit: "kg",
    availability: "Ready now",
    condition: "Organic",
    price: 1480,
    thumbnail: "/mock-products/rice.png",
  },
  {
    title: "Mango cartons",
    handle: "mock-mango-cartons",
    description: "Tree-ripened fruit packed in export cartons.",
    category: "Produce",
    location: "Battambang",
    quantity: "80",
    unit: "cartons",
    availability: "This week",
    condition: "Fresh",
    price: 2200,
    thumbnail: "/mock-products/mango.png",
  },
  {
    title: "Layer hens",
    handle: "mock-layer-hens",
    description: "Healthy laying birds from a small family farm.",
    category: "Livestock",
    location: "Siem Reap",
    quantity: "45",
    unit: "head",
    availability: "Ready now",
    condition: "Used",
    price: 950,
    thumbnail: "/mock-products/hens.png",
  },
  {
    title: "Cassava cuttings",
    handle: "mock-cassava-cuttings",
    description: "Vigorous planting material selected after harvest.",
    category: "Seeds",
    location: "Tboung Khmum",
    quantity: "15,000",
    unit: "cuttings",
    availability: "This month",
    condition: "Fresh",
    price: 320,
    thumbnail: "/mock-products/cassava.png",
  },
  {
    title: "Compact walking tractor",
    handle: "mock-compact-walking-tractor",
    description: "Serviced two-wheel tractor with rotary attachment.",
    category: "Equipment",
    location: "Takeo",
    quantity: "1",
    unit: "unit",
    availability: "Ready now",
    condition: "Used",
    price: 86000,
    thumbnail: "/mock-products/tractor.png",
  },
  {
    title: "Drip irrigation starter kit",
    handle: "mock-drip-irrigation-starter-kit",
    description: "Lines, connectors, filter, and valves for vegetable plots.",
    category: "Tools",
    location: "Phnom Penh",
    quantity: "12",
    unit: "sets",
    availability: "Ready now",
    condition: "New",
    price: 18500,
    thumbnail: "/mock-products/irrigation.png",
  },
  {
    title: "Compost fertilizer blend",
    handle: "mock-compost-fertilizer-blend",
    description: "Screened compost with rice husk and manure blend.",
    category: "Fertilizer",
    location: "Kandal",
    quantity: "300",
    unit: "bags",
    availability: "This week",
    condition: "Organic",
    price: 650,
    thumbnail: "/mock-products/compost.png",
  },
  {
    title: "Vegetable transplanting crew",
    handle: "mock-vegetable-transplanting-crew",
    description: "Experienced team available for seasonal field work.",
    category: "Services",
    location: "Prey Veng",
    quantity: "8",
    unit: "workers",
    availability: "Pre-order",
    condition: "Conventional",
    price: 4000,
    thumbnail: "/mock-products/seedlings.png",
  },
  {
    title: "Hybrid corn seed",
    handle: "mock-hybrid-corn-seed",
    description: "Sealed packs suitable for upland farms.",
    category: "Seeds",
    location: "Pursat",
    quantity: "60",
    unit: "packs",
    availability: "Ready now",
    condition: "New",
    price: 1250,
    thumbnail: "/mock-products/cassava.png",
  },
  {
    title: "Fresh duck eggs",
    handle: "mock-fresh-duck-eggs",
    description: "Collected daily and packed in trays.",
    category: "Produce",
    location: "Kampot",
    quantity: "500",
    unit: "trays",
    availability: "Ready now",
    condition: "Fresh",
    price: 420,
    thumbnail: "/mock-products/mango.png",
  },
  {
    title: "Used rice thresher",
    handle: "mock-used-rice-thresher",
    description: "Diesel thresher in working condition.",
    category: "Equipment",
    location: "Svay Rieng",
    quantity: "1",
    unit: "unit",
    availability: "This month",
    condition: "Used",
    price: 124000,
    thumbnail: "/mock-products/tractor.png",
  },
  {
    title: "Banana seedlings",
    handle: "mock-banana-seedlings",
    description: "Uniform seedlings ready for field planting.",
    category: "Seeds",
    location: "Kratie",
    quantity: "2,400",
    unit: "plants",
    availability: "This week",
    condition: "Organic",
    price: 180,
    thumbnail: "/mock-products/seedlings.png",
  },
  {
    title: "Hand sprayer bundle",
    handle: "mock-hand-sprayer-bundle",
    description: "Lightweight sprayers with spare nozzles.",
    category: "Tools",
    location: "Phnom Penh",
    quantity: "35",
    unit: "units",
    availability: "Ready now",
    condition: "New",
    price: 1550,
    thumbnail: "/mock-products/irrigation.png",
  },
  {
    title: "Goat manure sacks",
    handle: "mock-goat-manure-sacks",
    description: "Dry, aged manure for orchard and vegetable beds.",
    category: "Fertilizer",
    location: "Kep",
    quantity: "180",
    unit: "sacks",
    availability: "This week",
    condition: "Organic",
    price: 520,
    thumbnail: "/mock-products/compost.png",
  },
  {
    title: "Farm pond excavation",
    handle: "mock-farm-pond-excavation",
    description: "Excavator service for irrigation pond preparation.",
    category: "Services",
    location: "Banteay Meanchey",
    quantity: "3",
    unit: "slots",
    availability: "Pre-order",
    condition: "Conventional",
    price: 56000,
    thumbnail: "/mock-products/tractor.png",
  },
  {
    title: "Tilapia fingerlings",
    handle: "mock-tilapia-fingerlings",
    description: "Strong fingerlings from a managed hatchery.",
    category: "Livestock",
    location: "Kandal",
    quantity: "10,000",
    unit: "fish",
    availability: "This month",
    condition: "Fresh",
    price: 35,
    thumbnail: "/mock-products/hens.png",
  },
  {
    title: "Green papaya harvest",
    handle: "mock-green-papaya-harvest",
    description: "Firm fruit suitable for market stalls and processing.",
    category: "Produce",
    location: "Kampong Speu",
    quantity: "900",
    unit: "kg",
    availability: "Ready now",
    condition: "Fresh",
    price: 210,
    thumbnail: "/mock-products/mango.png",
  },
  {
    title: "Solar pump controller",
    handle: "mock-solar-pump-controller",
    description: "Controller and wiring kit for small irrigation pumps.",
    category: "Equipment",
    location: "Phnom Penh",
    quantity: "9",
    unit: "kits",
    availability: "Ready now",
    condition: "New",
    price: 27500,
    thumbnail: "/mock-products/irrigation.png",
  },
  {
    title: "Paddy drying tarps",
    handle: "mock-paddy-drying-tarps",
    description: "Heavy woven tarps for harvest drying yards.",
    category: "Tools",
    location: "Battambang",
    quantity: "70",
    unit: "pieces",
    availability: "Ready now",
    condition: "New",
    price: 3400,
    thumbnail: "/mock-products/seedlings.png",
  },
  {
    title: "Cattle mineral blocks",
    handle: "mock-cattle-mineral-blocks",
    description: "Trace mineral blocks for cattle and buffalo.",
    category: "Fertilizer",
    location: "Mondulkiri",
    quantity: "140",
    unit: "blocks",
    availability: "This week",
    condition: "New",
    price: 760,
    thumbnail: "/mock-products/compost.png",
  },
]

export const mockProducts = listings.map((listing, index) => {
  const createdAt = new Date(Date.UTC(2026, 5, 9 - index)).toISOString()

  const product = {
    id: `mock-product-${index + 1}`,
    title: listing.title,
    handle: listing.handle,
    subtitle: listing.category,
    description: listing.description,
    thumbnail: listing.thumbnail,
    images: [
      {
        id: `mock-image-${index + 1}`,
        url: listing.thumbnail,
      },
    ],
    variants: [
      {
        id: `mock-variant-${index + 1}`,
        title: "Default",
        calculated_price: {
          calculated_amount: listing.price,
          original_amount: listing.price,
          currency_code: "usd",
          calculated_price: {
            price_list_type: "default",
          },
        },
      },
    ],
    tags: [{ id: `mock-tag-${index + 1}`, value: listing.category }],
    created_at: createdAt,
    updated_at: createdAt,
    listing: {
      id: `mock-listing-${index + 1}`,
      status: "active",
      category: listing.category,
      location: listing.location,
      quantity: listing.quantity,
      unit: listing.unit,
      availability: listing.availability,
      condition: listing.condition,
      contact_preference: "Message",
      variety: null,
      production_method: listing.condition,
      harvest_date: null,
      breed: null,
      age: null,
      sex: null,
      health_notes: null,
      brand: null,
      equipment_model: null,
      year: null,
      pack_size: null,
      expiry_date: null,
      service_area: null,
    },
  }

  return product as unknown as StoreProductWithListing
})
