import type { StoreProductWithListing } from "@lib/data/products"

type MockListing = {
  title: string
  handle: string
  description: string
  category: string
  location: string
  quantity: string
  unit: string
  condition: "Fresh" | "Organic" | "Used" | "New"
  price: number
  thumbnail: string
}

const listings: MockListing[] = [
  {
    title: "Organic jasmine rice",
    handle: "organic-jasmine-rice-kampong-cham",
    description: "Cleaned new-season jasmine rice packed for pickup or local delivery.",
    category: "Produce",
    location: "Kampong Cham",
    quantity: "1,200",
    unit: "kg",
    condition: "Organic",
    price: 1480,
    thumbnail: "/mock-products/rice.png",
  },
  {
    title: "Fresh mango cartons",
    handle: "fresh-mango-cartons-battambang",
    description: "Tree-ripened Keo Romeat mangoes packed in market cartons.",
    category: "Produce",
    location: "Battambang",
    quantity: "80",
    unit: "cartons",
    condition: "Fresh",
    price: 2200,
    thumbnail: "/mock-products/mango.png",
  },
  {
    title: "Green papaya harvest",
    handle: "green-papaya-harvest-kampong-speu",
    description: "Firm green papaya suitable for market stalls and processing.",
    category: "Produce",
    location: "Kampong Speu",
    quantity: "900",
    unit: "kg",
    condition: "Fresh",
    price: 210,
    thumbnail: "/mock-products/mango.png",
  },
  {
    title: "Layer hens",
    handle: "layer-hens-siem-reap",
    description: "Healthy laying birds from a small family farm.",
    category: "Livestock",
    location: "Siem Reap",
    quantity: "45",
    unit: "head",
    condition: "Used",
    price: 950,
    thumbnail: "/mock-products/hens.png",
  },
  {
    title: "Tilapia fingerlings",
    handle: "tilapia-fingerlings-kandal",
    description: "Strong fingerlings from a managed hatchery.",
    category: "Livestock",
    location: "Kandal",
    quantity: "10,000",
    unit: "fish",
    condition: "Fresh",
    price: 35,
    thumbnail: "/mock-products/hens.png",
  },
  {
    title: "Young Boer goats",
    handle: "young-boer-goats-kampot",
    description: "Healthy young goats suitable for breeding or smallholder herds.",
    category: "Livestock",
    location: "Kampot",
    quantity: "18",
    unit: "head",
    condition: "Fresh",
    price: 64000,
    thumbnail: "/mock-products/hens.png",
  },
  {
    title: "Cassava cuttings",
    handle: "cassava-cuttings-tboung-khmum",
    description: "Vigorous planting material selected from healthy mother plants.",
    category: "Seeds",
    location: "Tboung Khmum",
    quantity: "15,000",
    unit: "cuttings",
    condition: "Fresh",
    price: 320,
    thumbnail: "/mock-products/cassava.png",
  },
  {
    title: "Hybrid corn seed",
    handle: "hybrid-corn-seed-pursat",
    description: "Sealed packs suitable for upland farms.",
    category: "Seeds",
    location: "Pursat",
    quantity: "60",
    unit: "packs",
    condition: "New",
    price: 1250,
    thumbnail: "/mock-products/cassava.png",
  },
  {
    title: "Banana seedlings",
    handle: "banana-seedlings-kratie",
    description: "Uniform seedlings ready for field planting.",
    category: "Seeds",
    location: "Kratie",
    quantity: "2,400",
    unit: "plants",
    condition: "Organic",
    price: 180,
    thumbnail: "/mock-products/seedlings.png",
  },
  {
    title: "Compost fertilizer blend",
    handle: "compost-fertilizer-blend-kandal",
    description: "Screened compost with rice husk and manure blend.",
    category: "Fertilizer",
    location: "Kandal",
    quantity: "300",
    unit: "bags",
    condition: "Organic",
    price: 650,
    thumbnail: "/mock-products/compost.png",
  },
  {
    title: "Cattle mineral blocks",
    handle: "cattle-mineral-blocks-mondulkiri",
    description: "Trace mineral blocks for cattle and buffalo.",
    category: "Fertilizer",
    location: "Mondulkiri",
    quantity: "140",
    unit: "blocks",
    condition: "New",
    price: 760,
    thumbnail: "/mock-products/compost.png",
  },
  {
    title: "Liquid biofertilizer",
    handle: "liquid-biofertilizer-takeo",
    description: "Fermented liquid input for vegetable and fruit farms.",
    category: "Fertilizer",
    location: "Takeo",
    quantity: "220",
    unit: "bottles",
    condition: "Organic",
    price: 1800,
    thumbnail: "/mock-products/compost.png",
  },
  {
    title: "Compact walking tractor",
    handle: "compact-walking-tractor-takeo",
    description: "Serviced two-wheel tractor with rotary attachment.",
    category: "Equipment",
    location: "Takeo",
    quantity: "1",
    unit: "unit",
    condition: "Used",
    price: 86000,
    thumbnail: "/mock-products/tractor.png",
  },
  {
    title: "Used rice thresher",
    handle: "used-rice-thresher-svay-rieng",
    description: "Diesel thresher in working condition.",
    category: "Equipment",
    location: "Svay Rieng",
    quantity: "1",
    unit: "unit",
    condition: "Used",
    price: 124000,
    thumbnail: "/mock-products/tractor.png",
  },
  {
    title: "Solar pump controller",
    handle: "solar-pump-controller-phnom-penh",
    description: "Controller and wiring kit for small irrigation pumps.",
    category: "Equipment",
    location: "Phnom Penh",
    quantity: "9",
    unit: "kits",
    condition: "New",
    price: 27500,
    thumbnail: "/mock-products/irrigation.png",
  },
  {
    title: "Drip irrigation starter kit",
    handle: "drip-irrigation-starter-kit-phnom-penh",
    description: "Lines, connectors, filter, and valves for vegetable plots.",
    category: "Tools",
    location: "Phnom Penh",
    quantity: "12",
    unit: "sets",
    condition: "New",
    price: 18500,
    thumbnail: "/mock-products/irrigation.png",
  },
  {
    title: "Paddy drying tarps",
    handle: "paddy-drying-tarps-battambang",
    description: "Heavy woven tarps for harvest drying yards.",
    category: "Tools",
    location: "Battambang",
    quantity: "70",
    unit: "pieces",
    condition: "New",
    price: 3400,
    thumbnail: "/mock-products/seedlings.png",
  },
  {
    title: "Pruning tool set",
    handle: "pruning-tool-set-kandal",
    description: "New hand pruners, folding saws, and sharpening stones for orchards.",
    category: "Tools",
    location: "Kandal",
    quantity: "24",
    unit: "sets",
    condition: "New",
    price: 9200,
    thumbnail: "/mock-products/irrigation.png",
  },
  {
    title: "Vegetable transplanting crew",
    handle: "vegetable-transplanting-crew-prey-veng",
    description: "Experienced team available for seasonal field work.",
    category: "Services",
    location: "Prey Veng",
    quantity: "8",
    unit: "workers",
    condition: "New",
    price: 4000,
    thumbnail: "/mock-products/seedlings.png",
  },
  {
    title: "Farm pond excavation",
    handle: "farm-pond-excavation-banteay-meanchey",
    description: "Excavator service for irrigation pond preparation.",
    category: "Services",
    location: "Banteay Meanchey",
    quantity: "3",
    unit: "slots",
    condition: "New",
    price: 56000,
    thumbnail: "/mock-products/tractor.png",
  },
  {
    title: "Mobile rice milling service",
    handle: "mobile-rice-milling-service-kampong-cham",
    description: "On-farm milling service available for small and medium paddy lots.",
    category: "Services",
    location: "Kampong Cham",
    quantity: "5",
    unit: "booking slots",
    condition: "New",
    price: 12000,
    thumbnail: "/mock-products/rice.png",
  },
  {
    title: "Farm storage drums",
    handle: "farm-storage-drums-phnom-penh",
    description: "Clean used drums for feed, grain, water, or tool storage.",
    category: "Other",
    location: "Phnom Penh",
    quantity: "40",
    unit: "drums",
    condition: "Used",
    price: 6500,
    thumbnail: "/mock-products/irrigation.png",
  },
  {
    title: "Organic mulch bales",
    handle: "organic-mulch-bales-kampong-speu",
    description: "Dry rice-straw mulch bales for vegetable beds and orchard rows.",
    category: "Other",
    location: "Kampong Speu",
    quantity: "260",
    unit: "bales",
    condition: "Organic",
    price: 900,
    thumbnail: "/mock-products/seedlings.png",
  },
  {
    title: "Used greenhouse netting",
    handle: "used-greenhouse-netting-siem-reap",
    description: "Shade netting removed from a vegetable house, still usable.",
    category: "Other",
    location: "Siem Reap",
    quantity: "600",
    unit: "meters",
    condition: "Used",
    price: 1400,
    thumbnail: "/mock-products/seedlings.png",
  },
]

export const mockProducts = listings.map((listing, index) => {
  const createdAt = new Date(Date.UTC(2026, 5, 28 - index)).toISOString()

  const product = {
    id: `mock-product-${index + 1}`,
    title: listing.title,
    handle: `mock-${listing.handle}`,
    subtitle: listing.category,
    description: listing.description,
    thumbnail: listing.thumbnail,
    images: [
      {
        id: `mock-image-${index + 1}`,
        url: listing.thumbnail,
      },
    ],
    variants: [
      {
        id: `mock-variant-${index + 1}`,
        title: "Listing price",
        calculated_price: {
          calculated_amount: listing.price,
          original_amount: listing.price,
          currency_code: "usd",
          calculated_price: {
            price_list_type: "default",
          },
        },
      },
    ],
    tags: [
      { id: `mock-category-tag-${index + 1}`, value: listing.category },
      { id: `mock-condition-tag-${index + 1}`, value: listing.condition },
    ],
    created_at: createdAt,
    updated_at: createdAt,
    listing: {
      id: `mock-listing-${index + 1}`,
      status: "active",
      category: listing.category,
      location: listing.location,
      quantity: listing.quantity,
      unit: listing.unit,
      condition: listing.condition,
    },
  }

  return product as unknown as StoreProductWithListing
})
